import { defineConfig } from '@hey-api/openapi-ts';

const outputPath = process.env.AXIOM_PLATFORM_CLIENT_OUTPUT ?? 'src/platform/generated';

export default defineConfig({
  input: './openapi/axiom-platform-v1.json',
  output: {
    clean: true,
    header: [
      '/* This file is auto-generated by @hey-api/openapi-ts 0.99.0. */',
      '/* Source: openapi/axiom-platform-v1.json. Do not edit generated files directly. */',
    ],
    path: outputPath,
  },
  plugins: [
    '@hey-api/client-fetch',
    '@hey-api/typescript',
    {
      name: '@hey-api/sdk',
      auth: false,
      client: '@hey-api/client-fetch',
      paramsStructure: 'grouped',
    },
    {
      name: 'zod',
      compatibilityVersion: 4,
    },
  ],
});
