import { AnalysisResult, ArchitectureDecision, ArchitectureOption, ClarificationQuestion, Gap, Requirement, RunMeta, ScoreDimension, SourceSpan } from './schemas';
export const projectId='PROJ-NOTIFYFLOW';
export const brief='Build a multi-tenant customer notification service for a SaaS product. It must support email and SMS, retries, delivery-status tracking, audit logs, and a simple admin dashboard. The first release should run on AWS and remain below USD 1,000 per month. We expect up to one million notifications per month. Customers must not see another tenant\'s data. The product team wants the first usable release quickly and expects the service to scale later.';
const docId='SRC-NOTIFYFLOW-BRIEF';
const now0=new Date(0).toISOString();
export const quoteSeeds=[['SP-001','multi-tenant customer notification service'],['SP-002','support email and SMS, retries, delivery-status tracking, audit logs, and a simple admin dashboard'],['SP-003','run on AWS and remain below USD 1,000 per month'],['SP-004','up to one million notifications per month'],['SP-005',"Customers must not see another tenant's data"],['SP-006','first usable release quickly']] as const;
export function deriveSpans(text:string,seeds: readonly (readonly [string,string])[]=quoteSeeds):SourceSpan[]{return seeds.flatMap(([id,quote])=>{const start=text.indexOf(quote);return start<0?[]:[{id,documentId:docId,quote,startOffset:start,endOffset:start+quote.length}];});}
export const spans=deriveSpans(brief);
const ev=(spanId:string)=>{const span=spans.find(s=>s.id===spanId);return span?[{spanId,quote:span.quote}]:[]};
const base=(id:string,truthStatus:'SOURCE_GROUNDED'|'AI_SUGGESTED'|'INFERRED'|'UNKNOWN'|'USER_PROVIDED'|'HUMAN_APPROVED'|'ESTIMATE'='SOURCE_GROUNDED', affectedEntityIds:string[]=[], spanId?:string)=>({id,projectId,truthStatus,affectedEntityIds,sourceEvidence:spanId?ev(spanId):[]});
export const functionalRequirements:Requirement[]=[{...base('FR-001','SOURCE_GROUNDED',[],'SP-002'),kind:'FUNCTIONAL',text:'Submit email and SMS notifications',priority:'P0'},{...base('FR-002','SOURCE_GROUNDED',[],'SP-002'),kind:'FUNCTIONAL',text:'Track delivery status and audit logs',priority:'P0'}];
export const nonFunctionalRequirements:Requirement[]=[{...base('NFR-SEC-001','SOURCE_GROUNDED',[],'SP-005'),kind:'NON_FUNCTIONAL',text:'Tenant data isolation required',priority:'P0'},{...base('NFR-COST-001','SOURCE_GROUNDED',[],'SP-003'),kind:'NON_FUNCTIONAL',text:'AWS MVP below USD 1,000/month',priority:'P0'},{...base('NFR-SCALE-001','SOURCE_GROUNDED',[],'SP-004'),kind:'NON_FUNCTIONAL',text:'One million notifications/month',priority:'P0'},{...base('NFR-DEL-001','SOURCE_GROUNDED',[],'SP-006'),kind:'NON_FUNCTIONAL',text:'First usable release quickly',priority:'P0'}];
export const requirements=[...functionalRequirements,...nonFunctionalRequirements].map(r=>({id:r.id,text:r.text,truth:r.truthStatus,span:r.sourceEvidence[0]?.spanId??''}));
export const initialGaps:Gap[]=[['GAP-LOAD','Peak request rate and latency target unknown','BLOCKER',['NFR-SCALE-001','NFR-PERF-001'],false,'SP-004'],['GAP-DELIVERY','Delivery semantics, idempotency, retry, and dead-letter policy unknown','BLOCKER',['FR-001','FR-002','NFR-REL-001'],false,'SP-002'],['GAP-RETENTION','Retention and data residency unknown','HIGH',['FR-002','NFR-COST-001','NFR-PRIV-001'],false,'SP-003'],['GAP-TENANT','Trusted tenant identity and isolation source unknown','BLOCKER',['NFR-SEC-001','FR-001'],true,'SP-005'],['GAP-PROVIDER','Provider outage behavior unknown','MEDIUM',['NFR-REL-001'],false,'SP-002']].map(([id,title,severity,affectedEntityIds,security,spanId])=>({...base(id as string,'UNKNOWN',affectedEntityIds as string[],spanId as string),title:title as string,severity:severity as Gap['severity'],resolved:false,security:security as boolean,rationale:'Missing information affects delivery design and verification.',sourceSpanIds:[spanId as string]}));
export const assumptions=[{...base('ASM-001','AI_SUGGESTED',['NFR-COST-001']),text:'AWS managed services are acceptable for the MVP.'}];
export const risks=[{...base('RISK-001','AI_SUGGESTED',['FR-001','FR-002']),title:'Provider outage',mitigation:'Use retries, dead-letter queue, and operator runbooks.'}];
export function makeQuestions(gaps=initialGaps):ClarificationQuestion[]{const mk=(id:string, gap:string[], text:string, why:string, affected:string[], opts:string[], priority:number):ClarificationQuestion=>({...base(id,'AI_SUGGESTED',affected),relatedGapIds:gap,text,whyItMatters:why,severity:gaps.find(g=>gap.includes(g.id)&&g.severity==='BLOCKER')?'BLOCKER':'HIGH',priority,options:opts.map((o,i)=>({id:`${id}-OPT-${i+1}`,label:o,value:o})),allowsCustomAnswer:true,answerStatus:'UNANSWERED',provenance:'AI_SUGGESTED',createdAt:now0,updatedAt:now0});return [mk('CQ-LOAD',['GAP-LOAD'],'What peak load and delivery target should the MVP design for?','Sets compute sizing, async boundaries, and performance tests.',['NFR-SCALE-001','NFR-PERF-001'],['100 requests/sec, bursts to 300; accept within 250 ms; 95% final status within 60 sec','Use monthly average only; defer burst target'],1),mk('CQ-DELIVERY',['GAP-DELIVERY'],'What delivery semantics, idempotency, retry, backoff, and dead-letter policy should apply?','Determines queue semantics, duplicate handling, and recovery evidence.',['FR-001','FR-002','NFR-REL-001'],['At-least-once with idempotency keys; 3 exponential retries then DLQ','Best effort with no DLQ'],2),mk('CQ-RETENTION',['GAP-RETENTION'],'What retention and AWS region/data residency constraints apply?','Constrains storage lifecycle, cost, privacy, and compliance assumptions.',['NFR-COST-001','NFR-PRIV-001'],['Metadata 90 days; message body 7 days; one approved AWS region','Retain all data for one year in any AWS US region'],3),mk('CQ-TENANT',['GAP-TENANT'],'Where does trusted tenant identity come from and how is isolation enforced?','Clears a P0 security blocker and prevents cross-tenant access by design.',['NFR-SEC-001','FR-001'],['Tenant ID from authenticated token, never request body alone','Tenant ID submitted in request body'],4)];}
export function answerQuestion(qs:ClarificationQuestion[],id:string,value:string,optionId?:string){const now=new Date().toISOString(); return qs.map(q=>q.id===id?{...q,answerStatus:'ANSWERED' as const,updatedAt:now,answer:{id:`ANS-${q.id}`,questionId:q.id,value,optionId,provenance:'USER_PROVIDED' as const,createdAt:q.answer?.createdAt??now,updatedAt:now}}:q)}
export function resolvedGaps(qs:ClarificationQuestion[], gaps=initialGaps){const answered=new Set(qs.filter(q=>q.answerStatus==='ANSWERED').flatMap(q=>q.relatedGapIds));return gaps.map(g=>({...g,resolved:answered.has(g.id)}));}
export function readiness(gaps:Gap[]){const cats=[['functional scope',20,20],['NFRs',20,gaps.some(g=>!g.resolved&&['GAP-LOAD','GAP-DELIVERY'].includes(g.id))?8:18],['data and integrations',15,gaps.some(g=>!g.resolved&&g.id==='GAP-RETENTION')?7:13],['error and edge cases',15,gaps.some(g=>!g.resolved&&g.id==='GAP-DELIVERY')?4:13],['security and privacy',10,gaps.some(g=>!g.resolved&&g.security)?3:9],['testability',10,gaps.some(g=>!g.resolved&&g.severity==='BLOCKER')?4:8],['delivery constraints',10,8]] as const; let total=cats.reduce((s,c)=>s+c[2],0); const blockers=gaps.filter(g=>!g.resolved&&g.severity==='BLOCKER'); if(blockers.length) total=Math.min(total,69); if(gaps.some(g=>!g.resolved&&g.security)) total=Math.min(total,79); return {total,categories:cats.map(([label,weight,score])=>({label,weight,score,items:[`${score}/${weight} deterministic checklist credit`]})),blockers,unknowns:gaps.filter(g=>!g.resolved)};}
export const dimensions:ScoreDimension[]=[{id:'fit',label:'Requirement/NFR fit',weight:25,ratings:{'ARCH-SERVERLESS':5,'ARCH-CONTAINER':4,'ARCH-KAFKA':3},truthStatus:'AI_SUGGESTED'},{id:'rel',label:'Reliability',weight:20,ratings:{'ARCH-SERVERLESS':4,'ARCH-CONTAINER':4,'ARCH-KAFKA':5},truthStatus:'AI_SUGGESTED'},{id:'sec',label:'Security and tenant isolation',weight:15,ratings:{'ARCH-SERVERLESS':4,'ARCH-CONTAINER':4,'ARCH-KAFKA':3},truthStatus:'AI_SUGGESTED'},{id:'speed',label:'Delivery speed',weight:15,ratings:{'ARCH-SERVERLESS':5,'ARCH-CONTAINER':4,'ARCH-KAFKA':2},truthStatus:'AI_SUGGESTED'},{id:'cost',label:'Cost fit',weight:15,ratings:{'ARCH-SERVERLESS':5,'ARCH-CONTAINER':3,'ARCH-KAFKA':1},truthStatus:'AI_SUGGESTED'},{id:'ops',label:'Operational burden and team fit',weight:10,ratings:{'ARCH-SERVERLESS':4,'ARCH-CONTAINER':3,'ARCH-KAFKA':1},truthStatus:'AI_SUGGESTED'}];
export const weighted=(id:string)=>dimensions.reduce((s,d)=>s+(d.ratings[id]??0)/5*d.weight,0);
export const options:ArchitectureOption[]=['ARCH-SERVERLESS','ARCH-CONTAINER','ARCH-KAFKA'].map((id,i)=>({...base(id,'AI_SUGGESTED',['FR-001','FR-002']),name:['Serverless event-driven','Containerized modular service','Kafka-based microservices'][i],summary:['API Gateway/Lambda/SQS design optimized for quick AWS MVP.','ECS/Fargate modular service with queue and relational storage.','Multiple services around Kafka/MSK for high-scale event streaming.'][i],components:['ingestion API','queue','provider adapters','status store','audit log'],dataFlows:['Client submits notification','Message is queued','Provider adapter sends email/SMS','Status and audit records update'],deploymentModel:['Managed serverless AWS services','ECS/Fargate services with managed database','MSK plus independently deployed microservices'][i],technologies:i===0?['API Gateway','Lambda','SQS','DynamoDB','CloudWatch']:i===1?['ECS/Fargate','SQS','PostgreSQL','CloudWatch']:['MSK/Kafka','container services','PostgreSQL','OpenTelemetry'],coverageRefs:['FR-001','FR-002','NFR-SEC-001','NFR-COST-001'],deliveryEffort:['Low','Medium','High'][i],scalability:['Scales with queue depth and Lambda concurrency','Scales by service/task count','Highest event-stream scale but more setup'][i],reliability:'Queue-backed retries and DLQ support at-least-once processing.',security:'Tenant ID must come from authenticated token and be enforced in every partition/query.',operationalBurden:['Low managed-ops burden','Moderate container/database operations','High broker and service operations'][i],teamSkillFit:['Best fit for fast MVP','Good if team prefers services','Poor for current MVP unless Kafka expertise exists'][i],vendorLockIn:['Moderate AWS managed-service lock-in','Moderate container portability','High operational commitment to Kafka platform'][i],monthlyCostRange:{min:[150,450,1800][i],max:[700,1100,4500][i],currency:'USD',assumptions:['Estimate only; depends on traffic, retention, and provider logs'],truthStatus:'ESTIMATE'},why:['Fits clarified MVP constraints','Supports explicit retry/DLQ and tenant isolation'],whyNot:[i===2?'Too much operational overhead for current scale':'Less suitable if long-running workflows or strict ordering dominate','Cost estimate is not verified evidence'],assumptions:['Seeded clarification answers remain valid','One approved AWS region is acceptable'],failureModes:[{mode:'Provider outage',mitigation:'Backoff, DLQ, and operator retry runbook'},{mode:'Duplicate delivery',mitigation:'Idempotency keys and status dedupe'}],reconsiderationTriggers:[i===2?'Sustained throughput exceeds 1,000 rps or cross-system ordering is required':'Monthly cost exceeds USD 1,000 for two consecutive months','P95 final status misses 60 seconds for a week']}));
export function approve(optionId:string, architectureOptions=options, graphVersion=1):ArchitectureDecision{const chosen=architectureOptions.find(o=>o.id===optionId)??architectureOptions[0];return {id:'ADR-001',version:1,decisionQuestion:'Which architecture should NotifyFlow use for the MVP?',selectedOptionId:chosen.id,rejectedAlternatives:architectureOptions.filter(o=>o.id!==chosen.id).map(o=>({optionId:o.id,whyRejected:o.whyNot})),rationale:chosen.why,approvedAssumptions:chosen.assumptions,risks:['Provider outage may delay delivery','Cost estimate requires real telemetry'],reconsiderationTriggers:chosen.reconsiderationTriggers,graphVersion,approvedAt:new Date().toISOString(),truthStatus:'HUMAN_APPROVED',stale:false};}
export function fixtureAnalysisResult(run:RunMeta):AnalysisResult{return AnalysisResult.parse({projectId,graphVersion:1,productObjective:'Deliver NotifyFlow notification service MVP from the submitted brief.',sourceDocument:{id:docId,projectId,title:'NotifyFlow brief',kind:'PRODUCT_BRIEF',content:brief,createdAt:now0},sourceSpans:spans,functionalRequirements,nonFunctionalRequirements,assumptions,risks,gaps:initialGaps,clarificationQuestions:makeQuestions(),architectureOptions:options,readinessInputs:{gapIds:initialGaps.map(g=>g.id),securityGapIds:initialGaps.filter(g=>g.security).map(g=>g.id),blockerGapIds:initialGaps.filter(g=>g.severity==='BLOCKER').map(g=>g.id)},run});}
