
import { z } from 'zod';
export const TruthStatus=z.enum(['SOURCE_GROUNDED','AI_SUGGESTED','UNKNOWN','USER_PROVIDED','HUMAN_APPROVED','ESTIMATE']);
export const Gap=z.object({id:z.string(),title:z.string(),severity:z.enum(['BLOCKER','HIGH','MEDIUM','LOW']),affectedEntityIds:z.array(z.string()),resolved:z.boolean().default(false),security:z.boolean().default(false),rationale:z.string(),sourceSpanIds:z.array(z.string())});
export const ClarificationOption=z.object({id:z.string(),label:z.string(),value:z.string()});
export const ClarificationAnswer=z.object({id:z.string(),questionId:z.string(),value:z.string(),optionId:z.string().optional(),provenance:z.literal('USER_PROVIDED'),createdAt:z.string(),updatedAt:z.string()});
export const ClarificationQuestion=z.object({id:z.string(),relatedGapIds:z.array(z.string()).min(1),text:z.string(),whyItMatters:z.string(),affectedEntityIds:z.array(z.string()).min(1),severity:z.enum(['BLOCKER','HIGH','MEDIUM','LOW']),priority:z.number(),options:z.array(ClarificationOption).min(2).max(4),allowsCustomAnswer:z.boolean(),answerStatus:z.enum(['UNANSWERED','ANSWERED']),provenance:TruthStatus,createdAt:z.string(),updatedAt:z.string(),answer:ClarificationAnswer.optional()});
export const FailureMode=z.object({mode:z.string(),mitigation:z.string()});
export const ArchitectureOption=z.object({id:z.string(),name:z.string(),summary:z.string(),components:z.array(z.string()).min(1),dataFlows:z.array(z.string()).min(1),deploymentModel:z.string(),technologies:z.array(z.string()).min(1),coverageRefs:z.array(z.string()).min(1),deliveryEffort:z.string(),scalability:z.string(),reliability:z.string(),security:z.string(),operationalBurden:z.string(),teamSkillFit:z.string(),vendorLockIn:z.string(),monthlyCostRange:z.object({min:z.number(),max:z.number(),currency:z.literal('USD'),assumptions:z.array(z.string()),truthStatus:z.literal('ESTIMATE')}),why:z.array(z.string()).min(1),whyNot:z.array(z.string()).min(1),assumptions:z.array(z.string()).min(1),failureModes:z.array(FailureMode).min(2),reconsiderationTriggers:z.array(z.string()).min(1),truthStatus:TruthStatus});
export const ScoreDimension=z.object({id:z.string(),label:z.string(),weight:z.number(),ratings:z.record(z.string(),z.number().min(0).max(5)),truthStatus:z.literal('AI_SUGGESTED')});
export const ArchitectureDecision=z.object({id:z.string(),version:z.number(),decisionQuestion:z.string(),selectedOptionId:z.string(),rejectedAlternatives:z.array(z.object({optionId:z.string(),whyRejected:z.array(z.string())})),rationale:z.array(z.string()),approvedAssumptions:z.array(z.string()),risks:z.array(z.string()),reconsiderationTriggers:z.array(z.string()),graphVersion:z.number(),approvedAt:z.string(),truthStatus:z.literal('HUMAN_APPROVED'),stale:z.boolean().default(false)});
export type Gap=z.infer<typeof Gap>;export type ClarificationQuestion=z.infer<typeof ClarificationQuestion>;export type ArchitectureOption=z.infer<typeof ArchitectureOption>;export type ArchitectureDecision=z.infer<typeof ArchitectureDecision>;export type ScoreDimension=z.infer<typeof ScoreDimension>;
