import Link from 'next/link';

import { getWorkItemReview } from '@/src/platform/work-items';

import { BacklogEligibilityProvider } from './backlog-eligibility-context';
import { ArtifactBaselineAction } from './artifact-baseline-action';
import { ArchitectureAction } from './architecture-action';
import { ArchitectureComparison } from './architecture-comparison';
import { GenerateBacklogAction } from './generate-backlog-action';
import { ReviewBacklogAction } from './review-backlog-action';

export const dynamic = 'force-dynamic';

function percentage(value: number) { return `${Math.round(value * 100)}%`; }

export default async function BacklogReviewPage({ params }: { params: Promise<{ organizationId: string; projectId: string }> }) {
  const { organizationId, projectId } = await params;
  const state = await getWorkItemReview(organizationId, projectId);
  const projectsHref = `/account/organizations/${encodeURIComponent(organizationId)}/projects`;
  return (
    <main className="account-shell">
      <header className="account-topbar"><Link href="/account"><span>A</span><b>Axiom</b></Link><p>Exact backlog review</p></header>
      <section className="account-card backlog-review-card" aria-labelledby="backlog-heading">
        <span className="landing-kicker"><i /> Governed Agile backlog</span>
        <h1 id="backlog-heading">Agile backlog preview</h1>
        <p>This page shows exact persisted WorkItem versions and their real human-review state. Nothing here publishes to Jira or Trello.</p>
        {state.status !== 'ready' ? <div className="account-state" role={state.status === 'forbidden' || state.status === 'unavailable' ? 'alert' : undefined}><h2>{state.status === 'unauthenticated' ? 'Authentication required' : state.status === 'forbidden' ? 'Access denied' : state.status === 'not-found' ? 'Project not found' : 'Backlog unavailable'}</h2><p>{state.status === 'unavailable' ? state.message : 'Return to the authorized project list and try again.'}</p><Link className="account-text-link" href={projectsHref}>Return to projects</Link></div> : null}
        {state.status === 'ready' ? <BacklogEligibilityProvider><div className="account-state">
          <div className="project-access-heading"><div><h2>{state.project.name}</h2><p>{state.project.id} · graph v{state.project.graphVersion} · {state.project.status.replaceAll('_', ' ')}</p></div><Link className="account-text-link" href={projectsHref}>Return to projects</Link></div>
          {state.readiness ? <section className="backlog-readiness" aria-labelledby="readiness-heading"><header><div><h2 id="readiness-heading">Current graph readiness</h2><p>Deterministic calculation from graph v{state.project.graphVersion}; it is not a model confidence score.</p></div><strong>{state.readiness.score}/100</strong></header><ol>{state.readiness.categories.map((category) => <li key={category.key}><div><b>{category.label}</b><span>{category.score}/{category.maximum}</span></div><p>{category.explanation}</p>{category.openGapIds.length ? <code>{category.openGapIds.join(', ')}</code> : null}</li>)}</ol>{state.readiness.caps.length ? <div className="backlog-readiness-caps"><b>Caps applied</b><ul>{state.readiness.caps.map((cap) => <li key={cap}>{cap}</li>)}</ul></div> : null}<small>Raw score {state.readiness.rawScore}/100 · calculated {new Date(state.readiness.calculatedAt).toLocaleString('en-IN', { timeZone: 'Asia/Kolkata' })}</small></section> : <div className="backlog-notice"><b>Readiness calculation unavailable</b><p>The current graph has no persisted deterministic readiness calculation. Artifact generation and approval remain unavailable until this is resolved.</p></div>}
          <section className="artifact-baseline" aria-labelledby="artifact-baseline-heading">
            <header><div><h2 id="artifact-baseline-heading">Requirement artifact baseline</h2><p>Exact compiled views of current graph v{state.artifactBaseline.graphVersion}. They are not Jira or Trello records.</p></div><strong>{state.artifactBaseline.approval ? 'APPROVED' : 'REVIEW REQUIRED'}</strong></header>
            {state.artifactBaseline.artifacts.length === 0 ? <div className="backlog-empty"><h3>No commercial baseline yet</h3><p>Legacy hackathon documents are excluded unless they satisfy the versioned provenance contract. Generate a new baseline from the current graph.</p></div> : <ol>{state.artifactBaseline.artifacts.map((artifact) => <li key={artifact.id}><details><summary><span>{artifact.title}</span><code>{artifact.type.toUpperCase()} · v{artifact.version}</code></summary><dl><div><dt>Exact SHA-256</dt><dd><code>{artifact.sha256}</code></dd></div><div><dt>Graph</dt><dd>v{artifact.sourceGraphVersion}</dd></div><div><dt>Truth</dt><dd>{artifact.truthStatus.replaceAll('_', ' ')}</dd></div><div><dt>Compiler</dt><dd><code>{artifact.provenance.compilerVersion}</code></dd></div></dl><pre>{artifact.content}</pre><small>Generated {new Date(artifact.generatedAt).toLocaleString('en-IN', { timeZone: 'Asia/Kolkata' })} · {artifact.provenance.sourceEntityIds.length} graph entities · {artifact.provenance.sourceIds.length} sources</small></details></li>)}</ol>}
            {state.artifactBaseline.approval ? <div className="artifact-approval-record"><div><b>Exact baseline approved</b><span>{state.artifactBaseline.approval.truthStatus.replaceAll('_', ' ')}</span></div><p>{state.artifactBaseline.approval.comment}</p><code>requirements {state.artifactBaseline.approval.documentHashes.requirements}<br />srs {state.artifactBaseline.approval.documentHashes.srs}<br />nfr {state.artifactBaseline.approval.documentHashes.nfr}</code><small>{state.artifactBaseline.approval.approvedByUserId} · {new Date(state.artifactBaseline.approval.approvedAt).toLocaleString('en-IN', { timeZone: 'Asia/Kolkata' })}</small></div> : null}
            {state.canManageArtifacts ? <ArtifactBaselineAction organizationId={organizationId} projectId={projectId} projectRowVersion={state.project.rowVersion} sourceGraphVersion={state.project.graphVersion} artifacts={state.artifactBaseline.artifacts} approval={state.artifactBaseline.approval} /> : <div className="backlog-notice"><b>Artifact workflow is read-only</b><p>Your role can inspect exact artifact versions and approval evidence but cannot regenerate or approve them.</p></div>}
          </section>
          <section className="architecture-baseline" aria-labelledby="architecture-baseline-heading">
            <header><div><h2 id="architecture-baseline-heading">Architecture comparison and decision</h2><p>Versioned options compiled from the exact approved requirement baseline. Recommendations are suggestions until explicit human approval.</p></div><strong>{state.architectureBaseline.decision ? 'APPROVED' : state.architectureBaseline.generation ? 'DECISION REQUIRED' : 'NOT GENERATED'}</strong></header>
            <ArchitectureComparison baseline={state.architectureBaseline} />
            <ArchitectureAction organizationId={organizationId} projectId={projectId} projectRowVersion={state.project.rowVersion} sourceGraphVersion={state.project.graphVersion} baseline={state.architectureBaseline} requirementBaselineApproved={state.artifactBaseline.approval !== null} canGenerate={state.canGenerateArchitecture} canApprove={state.canApproveArchitecture} />
          </section>
          {state.canGenerateBacklog ? <GenerateBacklogAction organizationId={organizationId} projectId={projectId} projectRowVersion={state.project.rowVersion} sourceGraphVersion={state.project.graphVersion} hasPreview={state.preview !== null} eligible={state.artifactBaseline.approval !== null && state.architectureBaseline.decision !== null && ['HLD_READY', 'PUBLISHED', 'BACKLOG_READY'].includes(state.project.status)} /> : <div className="backlog-notice"><b>Generation is read-only</b><p>Your role cannot generate a new draft version.</p></div>}
          {state.preview === null ? <div className="backlog-empty"><h2>No persisted draft</h2><p>Generate a policy-routed draft after the current graph, documents, and architecture are approved and blocking gaps are resolved.</p></div> : <>
            <section className="backlog-proof" aria-labelledby="quality-heading"><div><h2 id="quality-heading">Deterministic quality result</h2><p>Passed by {state.preview.evaluatorVersion}. Human edits are rerun through the same gates before acceptance.</p></div><strong>{state.preview.qualityReport.passed ? 'PASSED' : 'FAILED'}</strong><dl><div><dt>Schema</dt><dd>{state.preview.qualityReport.metrics.schemaValid ? 'Valid' : 'Invalid'}</dd></div><div><dt>Grounding</dt><dd>{percentage(state.preview.qualityReport.metrics.validSourceReferenceRate)}</dd></div><div><dt>Coverage</dt><dd>{percentage(state.preview.qualityReport.metrics.approvedRequirementCoverage)}</dd></div><div><dt>Items</dt><dd>{state.preview.qualityReport.metrics.workItemCount}</dd></div></dl></section>
            {state.preview.provenance ? <section className="backlog-proof" aria-labelledby="generation-proof-heading"><div><h2 id="generation-proof-heading">Generation evidence</h2><p>{state.preview.provenance.workflowVersion} · {state.preview.provenance.promptVersion}</p></div><strong>{state.preview.provenance.provider.replaceAll('_', ' ')}</strong><dl><div><dt>Tier</dt><dd>{state.preview.provenance.tier}</dd></div><div><dt>Model</dt><dd><code>{state.preview.provenance.immutableModelId}</code></dd></div><div><dt>Budget</dt><dd>{state.preview.provenance.budget.status === 'NOT_APPLICABLE' ? 'Non-billable local fixture' : `Reserved · ${state.preview.provenance.budget.reservationId}`}</dd></div><div><dt>Attempts</dt><dd>{state.preview.provenance.attemptCount}</dd></div></dl><small><code>{state.preview.provenance.runId} · {state.preview.provenance.modelCallId}</code></small></section> : <div className="backlog-notice"><b>Legacy generation</b><p>This draft predates Agent Kernel provenance. Regenerate it before relying on model evidence.</p></div>}
            <div className={`backlog-version status-${state.preview.status.toLowerCase()}`}><span>{state.preview.sourceGraphVersion !== state.project.graphVersion ? 'HISTORICAL DRAFT · REVIEW DISABLED' : state.preview.status.replaceAll('_', ' ')}{state.preview.status === 'DRAFT' && state.preview.sourceGraphVersion === state.project.graphVersion ? ' · awaiting human review' : ''}</span><code>{state.preview.id} · exact content {state.preview.contentHash}</code>{state.preview.contentHash !== state.preview.generationContentHash ? <code>Generated snapshot {state.preview.generationContentHash}</code> : null}<small>Graph v{state.preview.sourceGraphVersion} · generated {new Date(state.preview.generatedAt).toLocaleString('en-IN', { timeZone: 'Asia/Kolkata' })}</small></div>
            {state.preview.review ? <section className="backlog-review-record" aria-labelledby="recorded-review-heading"><div><h2 id="recorded-review-heading">Recorded human review</h2><strong>{state.preview.review.decision.replaceAll('_', ' ')}</strong></div><dl><div><dt>Reason</dt><dd>{state.preview.review.reasonCategory.replaceAll('_', ' ')}</dd></div><div><dt>Reviewer</dt><dd><code>{state.preview.review.reviewedByUserId}</code></dd></div><div><dt>Recorded</dt><dd>{new Date(state.preview.review.reviewedAt).toLocaleString('en-IN', { timeZone: 'Asia/Kolkata' })}</dd></div></dl><p>{state.preview.review.comment}</p><small>{state.preview.status === 'APPROVED' ? 'Approved for later connector preparation. No external publication has occurred.' : 'Rejected versions remain immutable. Generate a new draft after addressing the recorded reason.'}</small></section> : null}
            {state.preview.status === 'DRAFT' && state.preview.sourceGraphVersion === state.project.graphVersion && state.canReview ? <ReviewBacklogAction organizationId={organizationId} projectId={projectId} generationId={state.preview.id} generationContentHash={state.preview.generationContentHash} workItems={state.preview.workItems} /> : null}
            {state.preview.status === 'DRAFT' && state.preview.sourceGraphVersion === state.project.graphVersion && !state.canReview ? <div className="backlog-notice"><b>Review is read-only</b><p>Your role can inspect the exact draft but cannot accept, edit, or reject it.</p></div> : null}
            {state.preview.sourceGraphVersion !== state.project.graphVersion ? <div className="backlog-notice"><b>Historical graph evidence</b><p>This draft belongs to graph v{state.preview.sourceGraphVersion}. Generate and review a new draft only after graph v{state.project.graphVersion} documents and architecture are approved.</p></div> : null}
            <section aria-labelledby="items-heading"><h2 id="items-heading">Exact work-item versions</h2><ol className="backlog-items">{state.preview.workItems.map((item) => <li key={`${item.id}:${item.version}`}><article><header><div><span>{item.type}</span><h3>{item.title}</h3><code>{item.id} · v{item.version}</code></div><dl><div><dt>Priority</dt><dd>{item.priority}</dd></div><div><dt>Estimate</dt><dd>{item.estimate}</dd></div></dl></header>{item.userStory ? <p className="backlog-user-story">As a <b>{item.userStory.persona}</b>, I want to {item.userStory.capability}, so that {item.userStory.benefit}.</p> : null}<section><h4>Outcome</h4><p>{item.outcome}</p></section><section><h4>Context</h4><p>{item.context}</p></section><div className="backlog-columns"><section><h4>In scope</h4><ul>{item.scope.map((value) => <li key={value}>{value}</li>)}</ul></section><section><h4>Out of scope</h4>{item.outOfScope.length ? <ul>{item.outOfScope.map((value) => <li key={value}>{value}</li>)}</ul> : <p>None recorded.</p>}</section></div>{item.acceptanceCriteria.length ? <section><h4>Acceptance criteria</h4><ol className="acceptance-list">{item.acceptanceCriteria.map((criterion) => <li key={criterion.id}><b>{criterion.statement}</b><span>{criterion.verificationKind.replaceAll('_', ' ')} — {criterion.verificationMethod}</span><code>{criterion.sourceEntityIds.join(', ')}</code></li>)}</ol></section> : null}<div className="backlog-columns"><section><h4>Dependencies</h4><p>{item.dependencyIds.length ? item.dependencyIds.join(', ') : 'None recorded.'}</p></section><section><h4>Evidence expected</h4>{item.evidenceExpectations.length ? <ul>{item.evidenceExpectations.map((value) => <li key={value}>{value}</li>)}</ul> : <p>Defined by child items.</p>}</section></div>{item.risks.length ? <section><h4>Risks</h4><ul>{item.risks.map((risk) => <li key={risk.description}><b>{risk.impact}</b> — {risk.description} Mitigation: {risk.mitigation}</li>)}</ul></section> : null}<footer><span>Sources</span><code>{item.sourceEntityIds.join(', ')}</code><span>{item.truthStatus}</span></footer></article></li>)}</ol></section>
          </>}
        </div></BacklogEligibilityProvider> : null}
      </section>
    </main>
  );
}
