import Link from 'next/link';

import { getBusinessContextPage } from '@/src/platform/business-context';
import type { PlatformBusinessContextPreview } from '@/src/platform/contracts';
import { BusinessContextReviewAction } from './business-context-review-action';

export const dynamic = 'force-dynamic';

function ContextList({ title, empty, items }: { title: string; empty: string; items: PlatformBusinessContextPreview['outcomes'] }) {
  return <section className="business-context-panel"><h2>{title}</h2>{items.length === 0 ? <p>{empty}</p> : <ol>{items.map((item) => <li key={item.id}><p>{item.statement}</p><footer><span>{item.truthStatus.replaceAll('_', ' ')}</span><code>{item.sourceEntityId}{item.sourceId ? ` · ${item.sourceId}` : ''}</code></footer></li>)}</ol>}</section>;
}

export default async function BusinessContextPage({ params }: { params: Promise<{ organizationId: string; projectId: string }> }) {
  const { organizationId, projectId } = await params;
  const state = await getBusinessContextPage(organizationId, projectId);
  const projectsHref = `/account/organizations/${encodeURIComponent(organizationId)}/projects`;
  const projectHref = `${projectsHref}/${encodeURIComponent(projectId)}`;
  const unavailableTitle = state.status === 'unauthenticated' ? 'Authentication required' : state.status === 'forbidden' ? 'Access denied' : state.status === 'not-found' ? 'Project not found' : state.status === 'not-ready' ? 'Analyze sources first' : 'Business Context unavailable';
  return <main className="account-shell">
    <header className="account-topbar"><Link href="/account"><span>A</span><b>Axiom</b></Link><p>Business Context</p></header>
    <section className="account-card business-context-card" aria-labelledby="business-context-heading">
      <span className="landing-kicker"><i /> Business-first product grounding</span>
      <h1 id="business-context-heading">Business Context preview</h1>
      <p>This deterministic preview shows only what the current canonical graph supports. Missing outcomes, actors, workflows, measures, or experience applicability remain explicit unknowns.</p>
      {state.status !== 'ready' ? <div className="account-state" role={state.status === 'forbidden' || state.status === 'unavailable' ? 'alert' : undefined}><h2>{unavailableTitle}</h2><p>{state.status === 'unavailable' ? state.message : state.status === 'not-ready' ? 'Upload and analyze the current source set before Axiom classifies business context.' : 'Return to the authorized project list and try again.'}</p><Link className="account-text-link" href={state.status === 'not-ready' ? projectHref : projectsHref}>{state.status === 'not-ready' ? 'Open sources' : 'Return to projects'}</Link></div> : null}
      {state.status === 'ready' ? <div className="account-state business-context-workflow">
        <div className="project-access-heading"><div><h2>{state.project.name}</h2><p>{state.project.id} · graph v{state.project.graphVersion} · {state.project.status.replaceAll('_', ' ')}</p></div><nav aria-label="Project navigation"><Link className="account-text-link" href={projectHref}>Sources</Link><Link className="account-text-link" href={`${projectHref}/engineering-plan`}>Engineering Plan</Link><Link className="account-text-link" href={`${projectHref}/backlog`}>Backlog</Link></nav></div>
        <section className={`business-context-applicability status-${state.preview.applicability.status.toLowerCase().replaceAll('_', '-')}`} aria-labelledby="experience-applicability-heading"><div><span>Experience applicability</span><h2 id="experience-applicability-heading">{state.preview.applicability.status.replaceAll('_', ' ')}</h2><p>{state.preview.applicability.rationale}</p></div><dl><div><dt>Graph</dt><dd>v{state.preview.sourceGraphVersion}</dd></div><div><dt>Classified</dt><dd>{state.preview.coverage.classifiedEntityCount}/{state.preview.coverage.eligibleEntityCount}</dd></div><div><dt>Blockers</dt><dd>{state.preview.blockingGapIds.length}</dd></div></dl><code>{state.preview.contentHash}</code></section>
        {state.baseline.version ? <section className="business-context-version" aria-labelledby="business-context-version-heading"><div><span>Immutable Business Context</span><h2 id="business-context-version-heading">Version {state.baseline.version.version}</h2><p>Generated by {state.baseline.version.generatedByUserId} on {new Date(state.baseline.version.generatedAt).toLocaleString('en-IN', { timeZone: 'Asia/Kolkata' })}.</p></div><code>{state.baseline.version.id} · {state.baseline.version.contentHash}</code>{state.baseline.review ? <div className={`business-context-review-decision decision-${state.baseline.review.decision.toLowerCase().replaceAll('_', '-')}`}><b>{state.baseline.review.decision.replaceAll('_', ' ')}</b><p>{state.baseline.review.comment}</p><small>{state.baseline.review.feedbackCategory.replaceAll('_', ' ')} · {state.baseline.review.truthStatus.replaceAll('_', ' ')}</small>{state.baseline.review.proposedGraphChanges.length ? <ol>{state.baseline.review.proposedGraphChanges.map((change, index) => <li key={`${change.target}:${change.targetItemId ?? index}`}><b>{change.target.replaceAll('_', ' ')}</b><p>{change.proposedValue}</p><small>{change.status.replaceAll('_', ' ')}</small></li>)}</ol> : null}</div> : <p>Awaiting exact human review.</p>}</section> : null}
        <BusinessContextReviewAction organizationId={organizationId} projectId={projectId} projectRowVersion={state.project.rowVersion} preview={state.preview} baseline={state.baseline} canGenerate={['OWNER', 'ADMINISTRATOR', 'PRODUCT_ANALYST', 'ARCHITECT'].includes(state.organization.role)} canReview={['OWNER', 'ADMINISTRATOR', 'PRODUCT_ANALYST', 'ARCHITECT', 'REVIEWER'].includes(state.organization.role)} />
        {state.preview.unknowns.length ? <section className="business-context-unknowns" aria-labelledby="business-unknowns-heading"><h2 id="business-unknowns-heading">Decisions still needed</h2><ol>{state.preview.unknowns.map((unknown) => <li key={unknown.code}><b>{unknown.question}</b><p>{unknown.whyItMatters}</p><code>{unknown.code}</code></li>)}</ol></section> : null}
        <div className="business-context-grid"><ContextList title="Business outcomes" empty="No grounded business outcome is present." items={state.preview.outcomes} /><ContextList title="Actors" empty="No grounded actor is present." items={state.preview.actors} /><ContextList title="Operating workflows" empty="No grounded operating workflow is present." items={state.preview.workflows} /><ContextList title="Success measures" empty="No grounded success measure is present." items={state.preview.successMeasures} /></div>
        {state.preview.coverage.unclassifiedEntityIds.length ? <section className="business-context-unclassified"><h2>Unclassified current-graph entities</h2><p>These entities remain in canonical truth but are not silently forced into a business category.</p><code>{state.preview.coverage.unclassifiedEntityIds.join(', ')}</code></section> : null}
        <footer className="business-context-provenance"><span>Deterministic preview · no model or external side effect</span><code>{state.preview.compilerVersion} · compiled {new Date(state.preview.compiledAt).toLocaleString('en-IN', { timeZone: 'Asia/Kolkata' })}</code></footer>
      </div> : null}
    </section>
  </main>;
}
