import { z } from 'zod';
import { AnalysisResult, ArchitectureDecision, ArtifactPack } from '../domain/schemas';

const SafeGeneratedPath=z.string().min(1).max(160).regex(/^[a-zA-Z0-9._/-]+$/,'Generated paths may contain only safe relative-path characters').refine((path)=>!path.startsWith('/')&&!path.includes('..')&&!path.includes('\\'),{message:'Generated paths must be relative and cannot traverse directories'});
export const TraceLink=z.object({id:z.string().min(1),fromType:z.string().min(1),fromId:z.string().min(1),relation:z.enum(['derives','clarifies','constrains','selects','rejects','implements','tests','verifies','contradicts','supersedes']),toType:z.string().min(1),toId:z.string().min(1)}).strict();
export const CodeFileOperation=z.object({operation:z.literal('write'),path:SafeGeneratedPath,content:z.string().min(1).max(65536),linkedEntityIds:z.array(z.string().min(1)).min(1)}).strict();
export const CodeGenerationDraft=z.object({generationId:z.string().min(1),projectId:z.string().min(1),sourceGraphVersion:z.number().int().nonnegative(),selectedSliceId:z.literal('SLICE-NOTIFICATION-API-001'),generatedAt:z.iso.datetime(),provider:z.object({mode:z.literal('fixture'),name:z.literal('notifyflow-controlled-code-fixture')}).strict(),provenance:z.object({artifactIds:z.array(z.string().min(1)).min(4),decisionId:z.string().min(1),constitutionId:z.string().min(1),requirementIds:z.array(z.string().min(1)).min(1),ruleIds:z.array(z.string().min(1)).min(1)}).strict(),operations:z.array(CodeFileOperation).min(1).max(10)}).strict();
export const CodeFile=z.object({id:z.string().min(1),path:SafeGeneratedPath,content:z.string(),hash:z.string().regex(/^sha256:[a-f0-9]{64}$/),linkedEntityIds:z.array(z.string().min(1)).min(1),generationId:z.string().min(1),diff:z.string().min(1)}).strict();
export const CodeGenerationOutput=z.object({generationId:z.string().min(1),projectId:z.string().min(1),sourceGraphVersion:z.number().int().nonnegative(),selectedSliceId:z.literal('SLICE-NOTIFICATION-API-001'),generatedAt:z.iso.datetime(),provider:z.object({mode:z.literal('fixture'),name:z.literal('notifyflow-controlled-code-fixture')}).strict(),workspaceRoot:z.literal('sandbox/notification-service/workspace'),templateFiles:z.array(SafeGeneratedPath).min(1),manifestHash:z.string().regex(/^sha256:[a-f0-9]{64}$/),provenance:z.object({artifactIds:z.array(z.string().min(1)).min(4),decisionId:z.string().min(1),constitutionId:z.string().min(1),requirementIds:z.array(z.string().min(1)).min(1),ruleIds:z.array(z.string().min(1)).min(1)}).strict(),files:z.array(CodeFile).min(1).max(10),traceLinks:z.array(TraceLink).min(1)}).strict();
export const CodeApproval=z.object({generationId:z.string().min(1),manifestHash:z.string().regex(/^sha256:[a-f0-9]{64}$/),truthStatus:z.literal('HUMAN_APPROVED'),approvedAt:z.iso.datetime()}).strict();
export const CodeGenerationRequest=z.object({analysis:AnalysisResult,decision:ArchitectureDecision,artifactPack:ArtifactPack,selectedSliceId:z.literal('SLICE-NOTIFICATION-API-001')}).strict().refine((value)=>!value.decision.stale,{message:'Stale ADR must be re-approved before code generation',path:['decision','stale']}).refine((value)=>value.decision.graphVersion===value.analysis.graphVersion&&value.artifactPack.sourceGraphVersion===value.analysis.graphVersion,{message:'Analysis, ADR, and artifact pack graph versions must match',path:['artifactPack','sourceGraphVersion']}).refine((value)=>value.artifactPack.projectId===value.analysis.projectId,{message:'Artifact pack must belong to the analysis project',path:['artifactPack','projectId']}).refine((value)=>['adr','openapi','backlog','codex-task','constitution'].every((type)=>value.artifactPack.artifacts.some((artifact)=>artifact.type===type)),{message:'Artifact pack is missing required code-generation context',path:['artifactPack','artifacts']});

export type TraceLink=z.infer<typeof TraceLink>;export type CodeFileOperation=z.infer<typeof CodeFileOperation>;export type CodeGenerationDraft=z.infer<typeof CodeGenerationDraft>;export type CodeFile=z.infer<typeof CodeFile>;export type CodeGenerationOutput=z.infer<typeof CodeGenerationOutput>;export type CodeApproval=z.infer<typeof CodeApproval>;export type CodeGenerationRequest=z.infer<typeof CodeGenerationRequest>;
